# Example configuration for github.com/eryalito/multi-wordpress-file-manager
# Save this as config.yaml (or provide --config path)

sites:
  - name: example-site
    root: C:/inetpub/wwwroot/example-site
  - name: another-sites
    root: D:/wordpress/another
